### ISSUE TITLE
reindex_all causes NoMethodError: undefined method `split' on nil:NilClass.

### ISSUE THREAD

**Issue by sammcj** [Undev/redmine_elasticsearch#17]
* Redmine 2.6.0
* Debian 7
* Ruby 1.9.1 (Also tried on our default which is Rubinius 2.4.1)

```
root@dev-redmine:/var/vhost/dev-redmine 1 # ELASTICSEARCH_URL='int-elastic-01:9200' bundle exec rake redmine_elasticsearch:reindex_all RAILS_ENV=production --trace
Loading Rails environment for Resque
** Invoke redmine_elasticsearch:reindex_all (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine_elasticsearch:reindex_all
Recreate index for all available search types
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
/var/lib/gems/1.9.1/gems/active_model_serializers-0.9.3/lib/active_model/serializable.rb:46:in `get_namespace'
/var/lib/gems/1.9.1/gems/active_model_serializers-0.9.3/lib/active_model/serializable.rb:36:in `namespace'
/var/lib/gems/1.9.1/gems/active_model_serializers-0.9.3/lib/active_model/serializer.rb:231:in `association_options_for_serializer'
/var/lib/gems/1.9.1/gems/active_model_serializers-0.9.3/lib/active_model/serializer.rb:226:in `build_serializer'
/var/lib/gems/1.9.1/gems/active_model_serializers-0.9.3/lib/active_model/serializer.rb:240:in `serialize'
/var/lib/gems/1.9.1/gems/active_model_serializers-0.9.3/lib/active_model/serializer.rb:181:in `block in associations'
/var/lib/gems/1.9.1/gems/active_model_serializers-0.9.3/lib/active_model/serializer.rb:167:in `each'
/var/lib/gems/1.9.1/gems/active_model_serializers-0.9.3/lib/active_model/serializer.rb:167:in `each_with_object'
/var/lib/gems/1.9.1/gems/active_model_serializers-0.9.3/lib/active_model/serializer.rb:167:in `associations'
/var/lib/gems/1.9.1/gems/active_model_serializers-0.9.3/lib/active_model/serializer.rb:285:in `serializable_object'
/var/lib/gems/1.9.1/gems/active_model_serializers-0.9.3/lib/active_model/serializable.rb:16:in `block in as_json'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/notifications.rb:125:in `instrument'
/var/lib/gems/1.9.1/gems/active_model_serializers-0.9.3/lib/active_model/serializable.rb:55:in `instrument'
/var/lib/gems/1.9.1/gems/active_model_serializers-0.9.3/lib/active_model/serializable.rb:10:in `as_json'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/json/encoding.rb:47:in `block in encode'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/json/encoding.rb:77:in `check_for_circular_references'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/json/encoding.rb:46:in `encode'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/json/encoding.rb:31:in `encode'
/var/lib/gems/1.9.1/gems/activesupport-3.2.19/lib/active_support/core_ext/object/to_json.rb:16:in `to_json'
/var/vhost/dev-redmine/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/serializer_service.rb:5:in `serialize_to_json'
/var/vhost/dev-redmine/plugins/redmine_elasticsearch/app/elastic/application_search.rb:13:in `to_indexed_json'
/var/lib/gems/1.9.1/gems/tire-0.6.2/lib/tire/index.rb:531:in `convert_document_to_json'
/var/lib/gems/1.9.1/gems/tire-0.6.2/lib/tire/index.rb:232:in `block in bulk'
/var/lib/gems/1.9.1/gems/tire-0.6.2/lib/tire/index.rb:176:in `map'
/var/lib/gems/1.9.1/gems/tire-0.6.2/lib/tire/index.rb:176:in `bulk'
/var/vhost/dev-redmine/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/indexer_service.rb:52:in `block in update_search_klass_for_project'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/relation/batches.rb:72:in `find_in_batches'
/var/vhost/dev-redmine/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/indexer_service.rb:51:in `update_search_klass_for_project'
/var/vhost/dev-redmine/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/indexer_service.rb:20:in `block (2 levels) in reindex_all'
/var/vhost/dev-redmine/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/indexer_service.rb:19:in `each'
/var/vhost/dev-redmine/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/indexer_service.rb:19:in `block in reindex_all'
/var/vhost/dev-redmine/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/indexer_service.rb:43:in `call'
/var/vhost/dev-redmine/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/indexer_service.rb:43:in `block in for_each_parent_project'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/relation/batches.rb:21:in `block (2 levels) in find_each'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/relation/batches.rb:21:in `each'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/relation/batches.rb:21:in `block in find_each'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/relation/batches.rb:72:in `find_in_batches'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/relation/batches.rb:20:in `find_each'
/var/vhost/dev-redmine/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/indexer_service.rb:41:in `for_each_parent_project'
/var/vhost/dev-redmine/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/indexer_service.rb:18:in `reindex_all'
/var/vhost/dev-redmine/plugins/redmine_elasticsearch/lib/tasks/index.rake:18:in `block (2 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine_elasticsearch:reindex_all
```

I can see the index in elasticsearch but it doesn't contain much:

```
{
    •    _index: redmineapp_production
    •    _type: parent_project
    •    _id: 1
    •    _version: 1
    •    _score: 1
    •    _source: {
    ◦    id: 1
    ◦    is_public: true
    ◦    status_id: 1
    ◦    enabled_module_names: [
    ▪    issue_tracking
    ▪    wiki
    ▪    repository
    ▪    time_tracking
    ▪    calendar
    ◦    ]
    ◦    route_key: abc
    •    }
}
```

**Comment by nodecarter** [comment]
Hi @sammcj !

**Comment by sammcj** [comment]
Hi @nodecarter , thanks for your response.

This is already included in the plugin, so I can't add it twice:

```
root@dev-redmine:/var/vhost/dev-redmine/plugins  # grep -ri "active_model_serializers" *
redmine_elasticsearch/Gemfile.lock:    active_model_serializers (0.9.3)
redmine_elasticsearch/Gemfile.lock:  active_model_serializers
redmine_elasticsearch/Gemfile:gem 'active_model_serializers'
```

```
Using rake 10.4.2
Using i18n 0.6.11
Using multi_json 1.10.1
Using activesupport 3.2.19
Using builder 3.0.4
Using activemodel 3.2.19
Using erubis 2.7.0
Using journey 1.0.4
Using rack 1.4.5
Using rack-cache 1.2
Using rack-test 0.6.3
Using hike 1.2.3
Using tilt 1.4.1
Using sprockets 2.2.3
Using actionpack 3.2.19
Using mime-types 1.25.1
Using polyglot 0.3.5
Using treetop 1.4.15
Using mail 2.5.4
Using actionmailer 3.2.19
Using active_model_serializers 0.9.3
Using arel 3.0.3
Using tzinfo 0.3.43
Using activerecord 3.2.19
Using pg 0.18.1
Using activerecord-postgresql-adapter 0.0.1
Using activeresource 3.2.19
Using bundler 1.7.7
Using rack-ssl 1.3.4
Using json 1.8.2
Using rdoc 3.12.2
Using thor 0.19.1
Using railties 3.2.19
Using rails 3.2.19
Using acts-as-taggable-on 2.3.3
Using ansi 1.5.0
Using coderay 1.1.0
Using hashr 0.0.22
Using jquery-rails 3.1.2
Using kaminari 0.16.2
Using memcache-client 1.8.5
Using memcached 1.8.0
Using money 5.1.0
Using mono_logger 1.1.0
Using net-ldap 0.7.0
Using netrc 0.10.2
Using puma 2.10.2
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Using rack-protection 1.5.3
Using rbpdf 1.18.5
Using redis 3.2.0
Using redis-namespace 1.5.1
Using request_store 1.0.5
Using sinatra 1.4.5
Using vegas 0.1.11
Using resque 1.25.2
Using rufus-scheduler 3.0.9
Using resque-scheduler 4.0.0
Using rest-client 1.7.2
Using rouge 1.8.0
Using ruby-ole 1.2.11.8
Using spreadsheet 0.6.9
Using tire 0.6.2
Using vcard 0.2.12
Your bundle is complete!
Gems in the groups development, test and RAILS_ENV=production were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

**Comment by nodecarter** [comment]
@sammcj , can you try to install the latest version from master branch? I have added version to plugin's Gemfile.

**Comment by sammcj** [comment]
Yep, gimmie 5 I want to make sure it's a clean environment to test it on again.

**Comment by sammcj** [comment]
It's looking better - I can see the index is getting bigger and it hasn't crashed out yet.

```
root@dev-redmine:/var/vhost/dev-redmine 127 # ELASTICSEARCH_URL='int-elastic-01:9200' ./rbenvrun.sh bundle exec rake redmine_elasticsearch:reindex_all RAILS_ENV=production
Loading Rails environment for Resque
Recreate index for all available search types
Projects:        1% |                                                                                | ETA:  02:45:18
```

```
redmineapp_production
size: 32.2Mi (62.1Mi)
docs: 905 (905)
```

**Comment by sammcj** [comment]
WOW that is slow!

**Comment by nodecarter** [comment]
Yes, reindex all documents are slow. But ideally this task should be run only once. I'm closing this issue. Thanks!

**Comment by sammcj** [comment]
and boom!

endless:
```
[ERROR] socket option should be a String, a Fixnum, true, or false, retrying (2)...
[ERROR] socket option should be a String, a Fixnum, true, or false, retrying (3)...
[ERROR] socket option should be a String, a Fixnum, true, or false, retrying (4)...
[ERROR] socket option should be a String, a Fixnum, true, or false, retrying (5)...
[ERROR] Too many exceptions occured, giving up. The HTTP response was: socket option should be a String, a Fixnum, true, or false
[ERROR] socket option should be a String, a Fixnum, true, or false, retrying (1)...
```
But ES is hall fine and dandy (We use ES a lot so have a big cluster setup anyway).

**Comment by sammcj** [comment]
I'll log a separate issues for this.
