### ISSUE TITLE
Reindex all documents error "Can't create index"

### ISSUE THREAD

**Issue by alexander-st** [Undev/redmine_elasticsearch#26]
Dear all,

I just tried to install the elasticsearch plugin on my local machine for testing. 
I do not have much experience, so please be patient.
The command of point 6. is failing

bundle exec rake redmine_elasticsearch:reindex_all RAILS_ENV=production

I get the following error message

C:\Bitnami\redmine-3.0.2-0\apps\redmine\htdocs>bundle exec rake redmine_elastics
earch:reindex_all RAILS_ENV=production
DL is deprecated, please use Fiddle
ansi: 'gem install win32console' to use color on Windows
Loading Rails environment for Resque
Recreate index for all available search types
rake aborted!  100% |||||||||||||||||||||||||||||||||||||||||||| ETA:  --:--:--
RedmineElasticsearch::IndexerError: Can't create index:
{"error":"IndexCreationException[[redmineapp_production] failed to create index]
; nested: IllegalArgumentException[Custom Analyzer [search_analyzer] failed to f
ind filter under name [russian_morphology]]; ","status":400}
C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/lib
/redmine_elasticsearch/indexer_service.rb:74:in `create_index'
C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/lib
/redmine_elasticsearch/indexer_service.rb:12:in `recreate_index'
C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/lib
/redmine_elasticsearch/indexer_service.rb:17:in `reindex_all'
C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/lib
/tasks/index.rake:18:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine_elasticsearch:reindex_all
(See full trace by running task with --trace)

Any idea what went wrong?

Thank you for your help!

**Comment by alexander-st** [comment]
I rebooted the machine and restarted elasticsearch and now I get a different error message:
C:\Bitnami\redmine-3.0.2-0\apps\redmine\htdocs>bundle exec rake redmine_elastics
earch:reindex_all RAILS_ENV=production
DL is deprecated, please use Fiddle
ansi: 'gem install win32console' to use color on Windows
Loading Rails environment for Resque
Recreate index for all available search types
rake aborted!  100% |||||||||||||||||||||||||||||||||||||||||||| ETA:  --:--:--
NoMethodError: undefined method `scoped' for #<Class:0x64a25d8>
C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/app
/models/parent_project.rb:57:in `searching_scope'
C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/lib
/redmine_elasticsearch/indexer_service.rb:45:in `for_each_parent_project'
C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/lib
/redmine_elasticsearch/indexer_service.rb:18:in `reindex_all'
C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/lib
/tasks/index.rake:18:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine_elasticsearch:reindex_all
(See full trace by running task with --trace)

**Comment by mklatsky** [comment]
I am also receiving the error noted in the opening comments:

<pre>
# bundle exec rake redmine_elasticsearch:reindex_all RAILS_ENV=production
Loading Rails environment for Resque
Recreate index for all available search types
rake aborted!
Can't create index:
{"error":"IndexCreationException[[redmineapp_production] failed to create index]; nested: 
IllegalArgumentException[Custom Analyzer [search_analyzer] failed to find filter under name 
[russian_morphology]]; ","status":400}
/redmine/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/indexer_service.rb:74:in `create_index'
/redmine/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/indexer_service.rb:12:in `recreate_index'
/redmine/plugins/redmine_elasticsearch/lib/redmine_elasticsearch/indexer_service.rb:17:in `reindex_all'
/redmine/plugins/redmine_elasticsearch/lib/tasks/index.rake:18:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine_elasticsearch:reindex_all
(See full trace by running task with --trace)
</pre>

**Comment by alexander-st** [comment]
Still the same problem, I started yesterday from scratch to try again installing elasticsearch for Redmine. Everything works well until point 6. in the installation instruction. The problem is still the indexing. In the following the command with --trace

C:\Bitnami\redmine-3.0.2-0\apps\redmine\htdocs>bundle exec rake redmine_elastics
earch:reindex_all RAILS_ENV=production --trace
Your Gemfile lists the gem kaminari (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of
 just one of them later.
DL is deprecated, please use Fiddle
ansi: 'gem install win32console' to use color on Windows
Loading Rails environment for Resque
** Invoke redmine_elasticsearch:reindex_all (first_time)
** Invoke redmine_elasticsearch:logged (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine_elasticsearch:logged
** Execute redmine_elasticsearch:reindex_all
Recreate index for all available search types
rake aborted!
NoMethodError: undefined method `scoped' for #<Class:0x69432d8>
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.1/lib/
active_record/dynamic_matchers.rb:26:in `method_missing'
C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/app
/models/parent_project.rb:57:in `searching_scope'
C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/lib
/redmine_elasticsearch/indexer_service.rb:45:in `for_each_parent_project'
C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/lib
/redmine_elasticsearch/indexer_service.rb:18:in `reindex_all'
C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/lib
/tasks/index.rake:18:in `block (2 levels) in <top (required)>'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:240:in `call'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:240:in `block in execute'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:235:in `each'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:235:in `execute'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:179:in `block in invoke_with_call_chain'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchroniz
e'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:172:in `invoke_with_call_chain'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:165:in `invoke'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:150:in `invoke_task'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:106:in `block (2 levels) in top_level'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:106:in `each'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:106:in `block in top_level'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:115:in `run_with_threads'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:100:in `top_level'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:78:in `block in run'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:176:in `standard_exception_handling'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:75:in `run'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/bin/rake:33
:in `<top (required)>'
C:/Bitnami/redmine-3.0.2-0/ruby/bin/rake:23:in `load'
C:/Bitnami/redmine-3.0.2-0/ruby/bin/rake:23:in `<main>'
Tasks: TOP => redmine_elasticsearch:reindex_all

Please any help!?!?

**Comment by alexander-st** [comment]
I checked with other pages and from their side it was stated that this is a specific problem from the plugin. 

ANY HELP?
